### ISSUE TITLE
Preconditions check

### ISSUE THREAD

**Issue by mfinotti** [kairostech-sw/kairoshub#15]
Prima di procedere allo sviluppo è necessario accertarsi di alcune dinamiche al fine di poter procedere spediti con lo sviluppo. 

- [x] Automazione sui programmi di riscaldamento
- [x] Sensori TRV
- [x] Sensore Temperatura ambiente
- [ ] TRV MQTT Check 1
- [ ] TRV MQTT Check 2
- [ ] TRV MQTT Check 3

**Automazione sui programmi di riscaldamento**
Dovrebbe già essere presente una automazione che con trigger ogni minuto controlla se ci sono programmi di riscaldamento attivi e richiama il modulo appdaemon per gestire il riscaldamento. 

**Sensori TRV**
In homeassistant sono definiti 7 classi di sensori destinati alla ricezione dei valori delle valvole. Ogni classe di sensore sviluppa 4 sensori:
- Temperatura attuale
- Posizione della valvola
- livello batteria
- Temperatura target (comfort)
- Lastupdate

Controllare che per ogni classe di sensore siano presenti i propri sensori e che siano impostati sul giusto topic. Ogni classe di sensore è identificata con un numero progressivo, quindi **TV01**, **TV02** etc. 

**Sensore Temperatura ambiente**
In ogni impianto è presente un sensore temperatura ambiente che serve per regolare il valore dell'ambiente. Questo sensore è inserito in un'altro sensore e insieme ai valori della temperatura di ogni testa termostatica calcola la media della temperatura. Controllare che in tale sensore sono presenti tutti i sensori che rilevano la temperatura.

**MQTT Check 1**
Occorre effettuare un check sul comportamento delle TRV in base ad alcuni aspetti. Il caso d'uso vuole che la testa termostatica sia standalone, ovvero che una volta impostata una temperatura target essa lavori in autonomia. E' inoltre necessario tenere in considerazione la temperatura comfort impostata nel programma di riscaldamento.

1. Controllare che la trv invii **sempre** a seguito di particolari un nuovo messaggio sul topic predefinito. 
 
**MQTT Check 2** 
Stando a quanto riportato dalla documentazione riportata [qui](https://shelly-api-docs.shelly.cloud/gen1/#shelly-trv-overview) la TRV accetta dei comandi, nel nostro caso specifico è necessario testare il comportamento quando inviamo il comando per impostare la temperatura target. 
Ad esempio, parte il programma di riscaldamento 1, con temperatura comfort 22. Impostare il valore della temperatura comfort alla valvola. 
Di conseguenza, provare a produrre un messaggio sul topic `shellies/shellytrv-<id>/thermostat-name/0/target_t` con valore **22** e commentare il task con il comportamento riscontrato.

**MQTT Check 3**
E' necessario fare ulteriori check sul comportamento della testa all'invido di alcuni comandi e commentare il task con i comportamenti rilevati:
1. verificare il comportamento quando viene inviato un valore rilevato da un sensore esterno, ovvero: `shellies/shellytrv-<id>/thermostat-name/0/ext_t`
2. verificare il comportamento quando è attivo e disattivo _l'accelerated heating_. Attivare la funzione attraverso il comando sul topic `shellies/shellytrv-<id>/thermostat-name/0/accelerated_heating` impostare una temperatura target di poco più alta rispetto l'attuale (+1 grado), Sollecitare la testa al raggiungimento della temperatura e rilevare il comportamento della testa. Ripetere il test disabilitando la funzione e attendendo che la testa sia tornata alla temperatura ambiente.
3. verificare il comportamento della funzionalità boost_minutes attraverso il comando sul topic `shellies/shellytrv-<id>/thermostat-name/0/boost_minutes`

**Comment by christianorsini** [comment]
### command topics
La TRV accetta valori sul topic `shellies/shellytrv-<id>/thermostat/0/command/#`, dove **#** è un command topic descritto sulla [documentazione](https://shelly-api-docs.shelly.cloud/gen1/#shelly-trv-mqtt)
### accelerated_heating
Quando `accelerated_heating` è attiva,  la valvola viene aperta al 50%. 
Anche se la temperatura arriva alla **target_t**, la valvola rimane aperta e non vengono mandati aggiornamenti di alcun tipo sul topic `shellies/shellytrv-<id>/info`. 
Lo status viene aggiornato quando la temperatura ritorna allo stato presente prima di attivare **accelerated_heating**.
### boost_minutes
Se la modalità `boost_minutes` è attiva, la valvola viene aperta completamente per la durata del boost. 
La valvola viene aperta anche se la temperatura rilevata è maggiore della **target_t**
**boost_minutes** non tiene in considerazione i secondi. Quindi se si attiva all'orario "11:05:50" per 1 minuto, si disattiva all'orario "11:06:00".
