### ISSUE TITLE
Refactoring sensori e gruppi di sensori

### ISSUE THREAD

**Issue by mfinotti** [kairostech-sw/kairoshub#32]
A seguito del censimento dei nuovi sensori di classe TH e TV occorre rivedere i sensori aggregatori per il calcolo delle medie. 

- [x] Refactoring sensore temperatura media (globale)
- [x] Nuove entità zona notte
- [x] Nuovo sensore temperatura media zona notte
- [x] Nuovo sensore umidità media zona notte
- [x] Nuovo sensore posizione media tapparelle zona notte
- [x] Nuove entità zona giorno
- [x] Nuovo sensore temperatura media zona giorno
- [x] Nuovo sensore umidità media zona notte
- [x] Nuovo sensore posizione media tapparelle zona giorno

### Refactoring sensore temperatura media (globale)
Aggiungere al sensore esistente `sensor.temperatura` che si occupa del calcolo medio della temperatura tutti i nuovi sensori censiti. 

### Nuove entità zona notte
Aggiungere le entità di seguito per ogni stanza della zona notte

**Ambiente generico**
- [x] `sensor.TH1000_T` (temperatura)
- [x] `sensor.TH1000_H` (umidità)

**Stanza 1** (letto 1)
- [x] `input_text.ZN101` (nome stanza 1 zona notte)
- [x] `sensor.TH1011_T` (temperatura)
- [x] `sensor.TH1011_H` (umidità)
- [x] `sensor.TV1011_T` (temperatura)
- [x] `sensor.TV1012_T` (temperatura)
- [x] `sensor.RS1011_P` (posizione)
- [x] `sensor.RS1012_P` (posizione)
- [x] `sensor.TZ101` (sensore media temperatura stanza TH1011, TV1011, TV1012)
- [x] `sensor.RP101` (sensore media tapparelle stanza RS1011, RS1012)

**Stanza 2** (letto 2)
- [x] `input_text.ZN102` (nome stanza 2 zona notte)
- [x] `sensor.TH1021_T`
- [x] `sensor.TH1021_H`
- [x] `sensor.TV1021_T`
- [x] `sensor.TV1022_T`
- [x] `sensor.RS1021_P`
- [x] `sensor.RS1022_P`
- [x] `sensor.TZ102` (sensore media temperatura stanza)
- [x] `sensor.RP102` (sensore media tapparelle stanza)

**Stanza 3** (letto 3)
- [x] `input_text.ZN103` (nome stanza 3 zona notte)
- [x] `sensor.TH1031_T`
- [x] `sensor.TH1031_H`
- [x] `sensor.TV1031_T`
- [x] `sensor.TV1032_T`
- [x] `sensor.RS1031_P`
- [x] `sensor.RS1032_P`
- [x] `sensor.TZ103` (sensore media temperatura stanza)
- [x] `sensor.RP103` (sensore media tapparelle stanza)

**Stanza 4** (bagno 1)
- [x] `input_text.ZN104` (nome stanza 4 zona notte)
- [x] `sensor.TH1041_T`
- [x] `sensor.TH1041_H`
- [x] `sensor.TV1041_T`
- [x] `sensor.TV1042_T`
- [x] `sensor.RS1041_P`
- [x] `sensor.RS1042_P`
- [x] `sensor.TZ104` (sensore media temperatura stanza)
- [x] `sensor.RP104` (sensore media tapparelle stanza)

### Nuovo sensore temperatura media zona notte
Aggiungere un nuovo sensore per il calcolo della temperatura media di tutti i sensori censiti nella zona notte

- `sensor.TV01`
- `sensor.TV02`
- `sensor.TV03`
- `sensor.TH1000_T`
- `sensor.TZ101`
- `sensor.TZ102`
- `sensor.TZ103`
- `sensor.TZ104`

### Nuovo sensore umidità media zona notte
Aggiungere un nuovo sensore per il calcolo della umidità media di tutti i sensori censiti nella zona notte

- `sensor.TH1000_H`
- `sensor.TH1011_H`
- `sensor.TH1021_H`
- `sensor.TH1031_H`
- `sensor.TH1041_H`

### Nuovo sensore posizione media tapparelle zona notte

- `sensor.RS01`
- `sensor.RS02`
- `sensor.RS03`
- `sensor.RS101`
- `sensor.RP102`
- `sensor.RP103`
- `sensor.RP104`

### Nuove entità zona giorno 
Aggiungere le entità di seguito per ogni stanza della zona giorno

**Ambiente generico**
- [x] `sensor.TH2000_T` (temperatura)
- [x] `sensor.TH2000_H` (umidità)

**Stanza 1** (soggiorno)
- [x] `input_text.ZN201` (nome stanza 1 zona giorno)
- [x] `sensor.TV2011_T` (temperatura)
- [x] `sensor.TV2012_T` (temperatura)
- [x] `sensor.RS2011_P` (posizione)
- [x] `sensor.RS2012_P` (posizione)
- [x] `sensor.TZ201` (sensore media temperatura stanza TV2011, TV2012)
- [x] `sensor.RP201` (sensore media tapparelle stanza RS2011, RS2012)

**Stanza 2** (cucina)
- [x] `input_text.ZN202`
- [x] `sensor.TH2021_T`
- [x] `sensor.TH2021_H`
- [x] `sensor.TV2021_T`
- [x] `sensor.TV2022_T`
- [x] `sensor.RS2021_P`
- [x] `sensor.RS2022_P`
- [x] `sensor.TZ202` (sensore media temperatura stanza)
- [x] `sensor.RP202` (sensore media tapparelle stanza)

**Stanza 3** (bagno 2)
- [x] `input_text.ZN203`
- [x] `sensor.TH2031_T`
- [x] `sensor.TH2031_H`
- [x] `sensor.TV2031_T`
- [x] `sensor.TV2032_T`
- [x] `sensor.RS2031_P`
- [x] `sensor.RS2032_P`
- [x] `sensor.TZ203` (sensore media temperatura stanza)
- [x] `sensor.RP203` (sensore media tapparelle stanza)

### Nuovo sensore temperatura media zona giorno
Aggiungere un nuovo sensore per il calcolo della media di tutti i sensori censiti nella zona giorno

- `sensor.TV04`
- `sensor.TV05`
- `sensor.TV06`
- `sensor.TV07`
- `sensor.TH2000_T`
- `sensor.TZ201`
- `sensor.TZ202`
- `sensor.TZ203`

### Nuovo sensore umidità media zona giorno
Aggiungere un nuovo sensore per il calcolo della umidità media di tutti i sensori censiti nella zona giorno

- `sensor.TH2000_H`
- `sensor.TH2021_H`
- `sensor.TH2031_H`

### Nuovo sensore posizione media tapparelle zona giorno

- `sensor.RS04`
- `sensor.RS05`
- `sensor.RS06`
- `sensor.RP201`
- `sensor.RP202`
- `sensor.RP203`

**Comment by christianorsini** [comment]
###Gruppi
Aggiungere gruppi per TV/TH/RS per zone `GIORNO` e `NOTTE`, considerando i dispositivi XX01 e XX02 appartenenti alla zona NOTTE e i rimanenti alla zona GIORNO

**Comment by mfinotti** [comment]
@christianorsini Da sistemare la definizione dei sensori media, in quanto riportano solamente i sensori di nuova generazione. Vedi di seguito 

![Image](https://user-images.githubusercontent.com/1792518/211152265-20784fde-aded-4ebd-a169-226546be5e61.png)

In questo caso, come negli altri per zona giorno e zona notte bisogna aggiungere i sensori di vecchia generazione. 

Anomalia riscontrata per: 

- temperature_night_zone.yaml
- temperature_day_zone.yaml


La determinazione del sensore medio è da rivedere in quanto utilizza i sensori e non gli aggregati media definiti nei file temperature_night/dat.zone. La definizione dovrebbe essere del tipo: 

> - platform: min_max
  name: TZ100
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TZ101
    - sensor.TZ102
    - sensor.TZ103
    - sensor.TZ104

> - platform: min_max
  name: TZ200
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TZ201
    - sensor.TZ202
    - sensor.TZ203


> - platform: min_max
  name: Temperatura
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TZ100
    - sensor.TZ200

**Di conseguenza è necessario rimuovere il sensore _mean_ `Temperatura TV` in quanto è già calcolato a livello stanza.**

**Comment by mfinotti** [comment]
@christianorsini manca definizione dei sensori mean a livello stanza, anomalia riscontrata in humidity.yaml dove sono definiti solo quelli a livello zona (giorno / notte). 

Anche se al momento abbiamo un solo sensore per uniformità di informazione è opportuno creare un sensore mean a livello stanza del tipo: 

> - platform: min_max
  name: TH101
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH1011_humidity

ridefinire il gruppo media come di seguito:

> - platform: min_max
  name: TH100
  type: mean
  round_digits: 1
  entity_ids:
    - sensor.TH1001_humidity
    - sensor.TH1011_humidity
    - ...........................................
    -  .........................................

**Comment by mfinotti** [comment]
## Tapparelle
Seguire la stessa logica di definizione dei gruppi media della temperatura.

**Comment by christianorsini** [comment]
### THX001
I gruppi delle zone giorno 200 e notte 100 sia per umidità che temperatura hanno, oltre ad i sensori di umidità o temperaturamedia delle vare sottozone, il sensore THX001 corrispondente per l'umidità e la temperatura
